### ISSUE TITLE
Respond to yellow light

### ISSUE THREAD

**Issue by mngrwl** [level5-engineers/system-integration#4]
I was just reading our [team's TODO list](https://github.com/level5-engineers/system-integration/wiki/Team's-TODO-list). In the traffic light section - I realized that we would also need to track the _change_ in traffic light and factor the time in our decision, because of the Yellow light. Which document should I mention this in so that we remember this later?

For example, if the car is already at the intersection at a reasonable speed and the green turns to yellow at that very moment, it should carry on crossing. If the light is yellow from the beginning and the car hasn't reached the intersection, it should probably try to stop before the light turns red.

**Comment by jwdunn1** [comment]
Github is flexible. Adding it as an issue certainly works. We can track it, tie it to a milestone, and when it's complete, close it. Other option is to enhance the to-do's in the wiki. I've put the rough items as a start, but feel free to add more refinement there. Another option, you can create your own branch of the repo and add a note to self as a comment in the traffic light node (if you intend to tackle that node).

**Comment by jwdunn1** [comment]
I've created a project on the Projects tab. Try adding a card there as a reminder. Let's experiment!

**Comment by mngrwl** [comment]
I've linked this issue to a milestone in the project.
